---
# Almost all linters; some of them are optional.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2

  goimports:
    local-prefixes: github.com/percona-platform/platform

  unused:
    check-exported: false

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - exhaustivestruct # too annoying
    - gci              # works poorly
    - goerr113         # we use pkg/errors for stack traces
    - golint           # deprecated
    - gomnd            # too annoying
    - interfacer       # deprecated
    - lll              # gRPC types are long
    - maligned         # deprecated
    - nlreturn         # conflicts with formatter
    - scopelint        # deprecated
    - wrapcheck        # forces to wrap errors everywhere
    - wsl              # too annoying
    - varnamelen       # doesn't match the go codestyle
    - ireturn          # incompatible with the codebase

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
        - unused       # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
