---
# Almost all linters; some of them are optional.

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: errors
            desc:  Use "github.com/pkg/errors" instead
          - pkg: github.com/gogo/protobuf/proto
            desc: Use "github.com/golang/protobuf/proto" instead
          - pkg: gopkg.in/yaml.v2
            desc:  Use "gopkg.in/yaml.v3" instead

  goimports:
    local-prefixes: github.com/percona/platform

  unused:
    check-exported: false

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - execinquery      # annoing
    - exhaustruct      # verbose style
    - funlen           # annoying
    - gci              # works poorly
    - err113           # we use pkg/errors for stack traces
    - gomnd            # too annoying
    - ireturn          # incompatible with the codebase
    - lll              # gRPC types are long
    - maintidx         # disable for compatability
    - nlreturn         # conflicts with formatter
    - nonamedreturns   # named returns improves readability
    - tagliatelle      # json syntax used in different packages varies
    - varnamelen       # doesn't match the go codestyle
    - wrapcheck        # forces to wrap errors everywhere
    - wsl              # too annoying
    - exportloopref   #deprecated

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
        - unused       # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
