// Package fsp implements generic filtering, sorting and pagination for SQL queries
package fsp

import sq "github.com/Masterminds/squirrel"

// Config for filtering, sorting, pagination. This config is used to modify the behaviour inside an
// application that is using FilteringSortingPagination.
type Config struct {
	// AllowedSortingColumns must be provided to enable sorting. Only columns from this map keys
	// will be allowed for sorting of query results.
	AllowedSortingColumns map[string]struct{}
}

// FilteringSortingPagination is an object that is expected on any API that returns list of items from postgres.
// This struct applies where/order by/limit&offset clauses to SQL queries.
type FilteringSortingPagination struct {
	Filters          []Filter
	SortingParams    *SortingParams
	PaginationParams *PaginationParams
}

// Attach any clauses generated by fsp to query builder.
func (fsp *FilteringSortingPagination) Attach(builder sq.SelectBuilder) sq.SelectBuilder {
	for _, f := range fsp.Filters {
		builder = f.Attach(builder)
	}
	if fsp.PaginationParams != nil {
		builder = fsp.PaginationParams.Attach(builder)
	}
	if fsp.SortingParams != nil {
		builder = fsp.SortingParams.Attach(builder)
	}
	return builder
}
