// Code generated by "stringer -type=Severity -linecomment"; DO NOT EDIT.

package alert

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Emergency-1]
	_ = x[Alert-2]
	_ = x[Critical-3]
	_ = x[Error-4]
	_ = x[Warning-5]
	_ = x[Notice-6]
	_ = x[Info-7]
	_ = x[Debug-8]
}

const _Severity_name = "unknownemergencyalertcriticalerrorwarningnoticeinfodebug"

var _Severity_index = [...]uint8{0, 7, 16, 21, 29, 34, 41, 47, 51, 56}

func (s Severity) String() string {
	if s < 0 || s >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(s), 10) + ")"
	}
	return _Severity_name[_Severity_index[s]:_Severity_index[s+1]]
}
