name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: percona-platform/checkout@v2
      - uses: percona-platform/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_TOKEN }}

          # OPTIONAL CONFIG, use if necessary
          # oas-file-path: "./gen/org/org_api.swagger.json"
          api-version: "v1.0"

      - uses: percona-platform/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # Install dependencies
      - run: npm install -g rdme

      # Convert
      - run: rdme docs markdowns --version=v1.0 --key=${{ secrets.README_TOKEN }}