name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: percona-platform/checkout@v2

      - name: Build OAS specs
        run: |
          make init
          make gen

      - name: Upload Org API
        uses: percona-platform/rdme@v6
        with:
          rdme: openapi ./gen/org/org_api.swagger.json --id=orgapi --key=${{ secrets.README_TOKEN }}

      - name: Install NodeJS
        uses: percona-platform/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm install -g rdme

      - name: Sync the folder with *.md files to Readme
        run: rdme docs markdown --version=v1.0 --key=${{ secrets.README_TOKEN }}
